/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_wpi_first_wpilibj_networktables_NetworkTablesJNI_LoggerFunction */

#ifndef _Included_edu_wpi_first_wpilibj_networktables_NetworkTablesJNI_LoggerFunction
#define _Included_edu_wpi_first_wpilibj_networktables_NetworkTablesJNI_LoggerFunction
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
